#!/usr/bin/env php
<?php

use Socodo\Framework\Console;

/**
 * Load composer autoloader.
 */
require_once __DIR__ . '/vendor/autoload.php';

/**
 * Execute an console application.
 */
$console = new Console();
$console->handle();