<?php

namespace App\Controllers;

use App\Structures\WelcomeIndexResponse;
use Socodo\Framework\Controller\Controller;
use Psr\Http\Message\ServerRequestInterface;
use Socodo\Router\Attributes\Prefix;
use Socodo\Router\Attributes\Get;

#[Prefix('/')]
class Welcome extends Controller
{
    /**
     * Constructor.
     *
     * @param ServerRequestInterface $request
     */
    public function __construct (ServerRequestInterface $request)
    {
        parent::__construct($request);
        // TODO: Change the autogenerated stub
    }

    /**
     * Example of using controller and structure.
     *
     * @return WelcomeIndexResponse
     */
    #[Get('/')]
    public function index (): WelcomeIndexResponse
    {
        return WelcomeIndexResponse::from([
            'message' => 'Hello, World!'
        ]);
    }
}